name: Action 45

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: test
      run: |
        echo "i is: $i"
      name: Echo i
      env:
        i: "45"
